name: Build Evil Barney

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake unzip wget

    - name: Download HLSDK
      run: wget https://github.com/FWGS/hlsdk-portable/archive/refs/heads/master.zip -O hlsdk-portable-master.zip

    - name: Unzip HLSDK
      run: unzip hlsdk-portable-master.zip -d sdk

    - name: Configure CMake
      run: cmake -S sdk/hlsdk-portable-master -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: hlso
        path: build/
