name: Build Evil Barney

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Unzip SDK
        run: unzip hlsdk-portable-master.zip -d sdk

      - name: Configure CMake
        run: cmake -S sdk/hlsdk-portable-master -B build \
          -DXASH_LINUX=ON \
          -DXASH_X86=ON \
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j4

      - name: Upload .so file
        uses: actions/upload-artifact@v3
        with:
          name: hl-so
          path: build/dlls/hl.so
